<?php

namespace axenox\BDT\Behat\Contexts\UI5Facade;

use axenox\BDT\Behat\Common\BdtPaths;
use axenox\BDT\Behat\Common\ErrorManager;
use axenox\BDT\Behat\Common\Traits\AuthenticatorTimeStampingTrait;
use axenox\BDT\Behat\Common\Traits\DeadlockRetryTrait;
use axenox\BDT\Behat\Contexts\UI5Facade\Nodes\GenericHtmlNode;
use axenox\BDT\Behat\Contexts\UI5Facade\Nodes\UI5PageNode;
use axenox\BDT\Behat\Contexts\UI5Facade\Nodes\UI5TileNode;
use axenox\BDT\Behat\DatabaseFormatter\DatabaseFormatter;
use axenox\BDT\Behat\Events\AfterPageVisited;
use axenox\BDT\Behat\Events\BeforeUserLoggedIn;
use axenox\BDT\Interfaces\FacadeNodeInterface;
use Behat\Mink\Element\DocumentElement;
use Behat\Mink\Element\ElementInterface;
use Behat\Mink\Element\NodeElement;
use Behat\Mink\Session;
use exface\Core\Actions\Login;
use exface\Core\CommonLogic\Security\AuthenticationToken\MetamodelUsernamePasswordAuthToken;
use exface\Core\CommonLogic\Security\Authenticators\MetamodelAuthenticator;
use exface\Core\CommonLogic\Workbench;
use exface\Core\DataTypes\ComparatorDataType;
use exface\Core\DataTypes\StringDataType;
use exface\Core\Exceptions\InvalidArgumentException;
use exface\Core\Exceptions\RuntimeException;
use exface\Core\Factories\ActionFactory;
use exface\Core\Factories\DataSheetFactory;
use exface\Core\Factories\FacadeFactory;
use exface\Core\Factories\MetaObjectFactory;
use exface\Core\Factories\UiPageFactory;
use exface\Core\Interfaces\Debug\LogBookInterface;
use exface\Core\Interfaces\Model\UiPageInterface;
use exface\Core\Interfaces\WidgetInterface;
use exface\Core\Interfaces\WorkbenchInterface;
use exface\UI5Facade\Facades\UI5Facade;
use PHPUnit\Framework\Assert;
use PHPUnit\Framework\AssertionFailedError;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Throwable;

/**
 * Allows to work with OpenUI5 apps generated by exface.UI5Facade
 *
 *  This class provides methods for:
 * - Finding and interacting with UI5 controls
 * - Navigating within UI5 applications
 * - Handling UI5-specific wait conditions
 * - Monitoring AJAX/XHR requests
 * - Validating UI states and content
 *
 * @author Andrej Kabachnik
 */
class UI5Browser
{
    use AuthenticatorTimeStampingTrait;
    use DeadlockRetryTrait;

    private const USER_PROVISIONING_LOCK_TIMEOUT_SECONDS = 60;
    private EventDispatcherInterface $eventDispatcher;
    private Session $session;
    private Workbench $workbench;
    private ?UI5Facade $facade = null;
    private UI5WaitManager $waitManager;
    private UI5ErrorDetector $errorDetector;
    private array $focusStack = [];
    private array $pagesVisited = [];
    private string $locale;
    /**
     * Role aliases that were applied to the test user in the current scenario via
     * {@see setupUser()}. Stored here so that any node can retrieve them through
     * {@see getCurrentRoles()} without needing to pass roles down through every call chain.
     *
     * @var string[]
     */
    private array $currentRoles = [];
    /** @var callable|null */
    private $navigator = null;
    /** @var callable|null */
    private $screenshotFn = null;

    // How long a lane waits for the user provisioning mutex before giving up and provisioning
    // unserialized. Sized well above a normal provisioning cycle (about a second) so contention among
    // four lanes never trips it, yet far below the worker idle timeout so a wedged holder can never
    // be the reason a lane is declared hung.
    /** @var callable|null */
    private $chromeRecoveryFn = null;

    /**
     * Constructor - initializes the UI5Browser with necessary dependencies
     *
     * @param WorkbenchInterface $workbench The application workbench
     * @param mixed $session session for browser interaction
     * @param string $ui5AppUrl URL of the UI5 application to load
     * @throws RuntimeException
     */
    public function __construct(WorkbenchInterface $workbench, Session $session, EventDispatcherInterface $eventDispatcher, string $ui5AppUrl, string $locale)
    {
        $this->eventDispatcher = $eventDispatcher;
        $this->session = $session;
        $this->workbench = $workbench;
        $this->waitManager = new UI5WaitManager($session);
        $this->errorDetector = new UI5ErrorDetector($session);
        $this->locale = $locale;
        $this->pagesVisited[] = StringDataType::substringBefore($ui5AppUrl, '.html');

        // Clear error log
        ErrorManager::getInstance()->clearErrors();
        // Initial app load using waitManager to ensure it's fully loaded
        $this->waitManager->waitForAppLoaded($ui5AppUrl);
    }

    public static function setupUser(WorkbenchInterface $workbench, array $roles, string $locale = null): array
    {
        $config = $workbench->getApp('axenox.BDT')->getConfig();
        $baseUsername = $config->getOption('TEST_USER.USERNAME');
        $testRunnerPassword = $config->getOption('TEST_USER.PASSWORD');

        // In a parallel run each worker carries a lane_id (wired through DatabaseFormatter). Give every
        // lane its OWN exface.Core.USER row by suffixing the username, so concurrent workers never
        // read-modify-write the same user row. Sharing one row across lanes breaks in two ways:
        //   1. the concurrent dataUpdate() below fails the optimistic-lock check, and
        //   2. roles cross-contaminate: dataUpdate() OVERWRITES USER_ROLE_USERS, so the last writer wins
        //      while both browser sessions are logged in under the same username — a scenario can then
        //      silently run with another lane's roles.
        // Only the stable "_laneN" slot is appended, never the full run-scoped lane_id, so the set of
        // test users stays bounded to the worker count and is reused on every nightly run instead of
        // piling up a fresh row each night. In the single-process path getLaneId() is null, so the
        // username and all existing behavior are unchanged.
        $laneId = DatabaseFormatter::getLaneId();
        $testRunnerUsername = $laneId !== null
            ? $baseUsername . self::laneUserSuffix($laneId)
            : $baseUsername;


        // Everything that touches exface.Core.USER / USER_ROLE_USERS runs under a cross-process
        // mutex. WHY: the nested-sheet write below is expanded by the core into a delete-then-insert
        // over USER_ROLE_USERS, and each insert fires PreventDuplicatesBehavior, which READS the same
        // table from inside the same transaction. Lanes have their own USER row, but their ROLE sets
        // overlap heavily, so the duplicate-check reads of one lane cover index ranges another lane is
        // concurrently rewriting - and the two long transactions form a lock cycle. Five deadlock
        // victims in one nightly run all traced to exactly this call. Provisioning takes about a
        // second and gains nothing from running concurrently, so serializing it removes the cycle by
        // construction instead of tuning around it.
        $provisioningLock = self::acquireUserProvisioningLock($workbench);
        try {
            $userSheet = DataSheetFactory::createFromObjectIdOrAlias($workbench, 'exface.Core.USER');
            $userSheet->getFilters()->addConditionFromString('USERNAME', $testRunnerUsername, ComparatorDataType::EQUALS);
            $userSheet->getColumns()->addFromSystemAttributes();
            // LOCALE is read (not just written) so an unchanged locale can be detected and skipped -
            // see the change check below.
            $userSheet->getColumns()->addMultiple([
                'USERNAME',
                'LOCALE'
            ]);
            $userSheet->dataRead();
            if ($userSheet->isEmpty()) {
                $userSheet->addRow([
                    'USERNAME' => $testRunnerUsername,
                    'PASSWORD' => $testRunnerPassword,
                    'FIRST_NAME' => $config->getOption('TEST_USER.FIRST_NAME'),
                    'LAST_NAME' => $config->getOption('TEST_USER.LAST_NAME'),
                    'LOCALE' => $workbench->getConfig()->getOption('SERVER.DEFAULT_LOCALE')
                ]);
                $userSheet->dataCreate();
            }
            $userId = $userSheet->getUidColumn()->getValue(0);

            $localeChanged = false;
            if ($locale) {
                $localeChanged = ((string)$userSheet->getCellValue('LOCALE', 0)) !== $locale;
                if ($localeChanged) {
                    $userSheet->setCellValue('LOCALE', 0, $locale);
                }
            }

            // Initialized up front because the BeforeUserLoggedIn dispatch at the end of this method
            // reads it unconditionally - with no roles requested it would otherwise be an undefined
            // variable.
            $roleAliasCol = null;
            $rolesChanged = false;

            if (!empty($roles)) {
                $roleSheet = DataSheetFactory::createFromObjectIdOrAlias($workbench, 'exface.Core.USER_ROLE');
                $roleSheet->getColumns()->addFromSystemAttributes();
                $roleAliasCol = $roleSheet->getColumns()->addFromExpression('ALIAS_WITH_NS');
                $roleUidCol = $roleSheet->getUidColumn();
                $roleSheet->getFilters()
                    ->addNestedOR()
                    ->addConditionFromValueArray('ALIAS_WITH_NS', $roles)
                    ->addConditionFromValueArray('NAME', $roles);
                $roleSheet->dataRead();
                Assert::assertEquals(count($roles), $roleSheet->countRows(), 'From the requested ' . count($roles) . ' user roles only the following were found: ' . implode(', ', $roleAliasCol->getValues()));

                $wantedRoleUids = $roleUidCol->getValues();

                // Only rewrite the role assignment when it actually differs. WHY THIS IS THE BIGGEST
                // WIN: iLogInToPage() runs in every scenario's Background, so a feature with ten
                // scenarios used to perform ten identical delete-and-reinsert cycles over
                // USER_ROLE_USERS - ten chances to deadlock, all of them writing exactly what was
                // already there. Comparing first turns dozens of contended transactions per run into
                // a handful that carry a real change.
                $currentRoleUids = self::readAssignedRoleUids($workbench, $userId);
                $rolesChanged = !self::isSameUidSet($currentRoleUids, $wantedRoleUids);

                if ($rolesChanged) {
                    $userRoleSheet = DataSheetFactory::createFromObjectIdOrAlias($workbench, 'exface.Core.USER_ROLE_USERS');
                    $userRoleSheet->getFilters()->addConditionFromString('USER', $userId);
                    foreach ($wantedRoleUids as $roleUid) {
                        $userRoleSheet->addRow([
                            'USER_ROLE' => $roleUid
                        ]);
                    }
                    $userSheet->setCellValue('USER_ROLE_USERS', 0, $userRoleSheet->exportUxonObject()->toArray());
                }
            }

            // No change at all means no transaction at all - and a transaction that never runs can
            // never be a deadlock victim.
            if ($rolesChanged || $localeChanged) {
                // The lock above cannot cover the web server, which writes the same user tables from
                // its own process while the browser session logs in. Being chosen as a victim there is
                // the documented, retryable outcome - the transaction was rolled back whole.
                self::runWithDeadlockRetry(
                    function () use ($userSheet) {
                        $userSheet->dataUpdate();
                    },
                    'test user provisioning for "' . $testRunnerUsername . '"',
                    $workbench->getLogger()
                );
            }
        } finally {
            self::releaseUserProvisioningLock($provisioningLock);
        }

        // Change the currently logged-in user to make sure the facade nodes "see" exaclty the same as the user in
        // the scenario. This is important because different users see slightly different UIs. If the scenario user
        // Only sees two tiles of four, they will have ids "Tile" and "Tile02" while a SUPERUSER might see more
        // tiles on the same page, where there would be also ids "Tile" and "Tile02", but those would be different
        // tiles if the scenario user is not allowed to see the first couple of tiles in the menu (in this case,
        // his "first" tile is different from the SUPERUSERs first tile).
        $testRunnerToken = new MetamodelUsernamePasswordAuthToken(
            $testRunnerUsername,
            $testRunnerPassword,
        );

        // The browser is about to submit the very same credentials to the web server, which writes the
        // same USER_AUTHENTICATOR row from another process. Without the guard the two writers race on
        // the row's optimistic lock and the lane dies with "changed in the meantime".
        self::withoutAuthenticatorTimeStamping(
            $workbench,
            fn() => $workbench->getSecurity()->authenticate($testRunnerToken)
        );

        $loginFields = [];
        // Make sure to get login form field names the way an anonymous user would see them
        $localeOfTestRunner = $workbench->getContext()->getScopeSession()->getSessionLocale();
        $localeOfAnonymous = $workbench->getConfig()->getOption('SERVER.DEFAULT_LOCALE');
        $workbench->getContext()->getScopeSession()->setSessionLocale($localeOfAnonymous);
        foreach ($workbench->getConfig()->getOption('SECURITY.AUTHENTICATORS') as $authUxon) {
            if ($authUxon->getProperty('class') === '\\' . MetamodelAuthenticator::class) {
                $loginDataObj = MetaObjectFactory::createFromString($workbench, 'exface.Core.LOGIN_DATA');
                $loginFields['_tab'] = $authUxon->getProperty('name') ?? $workbench->getCoreApp()->getTranslator($localeOfAnonymous)->translate('SECURITY.SIGN_IN');
                $loginFields[$loginDataObj->getAttribute('USERNAME')->getName()] = $testRunnerUsername;
                $loginFields[$loginDataObj->getAttribute('PASSWORD')->getName()] = $testRunnerPassword;
                $loginAction = ActionFactory::createFromString($workbench, Login::class);
                $loginFields['_button'] = $loginAction->getName();
                break;
            }
        }
        $workbench->getContext()->getScopeSession()->setSessionLocale($localeOfTestRunner);

        // Fire an on-before-login event to publish the roles
        if ($roleAliasCol !== null) {
            $roleAliasArray = $roleAliasCol->getValues();
        } else {
            $roleAliasArray = [];
        }
        DatabaseFormatter::getEventDispatcher()->dispatch(new BeforeUserLoggedIn($testRunnerUsername, $roleAliasArray));

        return $loginFields;
    }

    /**
     * Derives the stable per-lane username suffix from a lane_id.
     *
     * Why only the trailing "_laneN" and not the whole lane_id: lane_id is built by the coordinator
     * as "<run_uid>_laneN". The run_uid changes every night, so embedding it would create a brand new
     * user row on every run and let test users accumulate without bound. Keeping just "_laneN" makes
     * the username identical across runs, so find-or-create reuses the same row and the user set stays
     * capped at the worker count.
     *
     * Why it throws instead of falling back: if we are in a parallel run (lane_id present) but cannot
     * locate the lane slot, silently using the base username would put every lane back on one shared
     * row — the exact collision this change exists to prevent. Failing loudly surfaces a broken
     * lane_id contract instead of hiding it behind a data race.
     */
    private static function laneUserSuffix(string $laneId): string
    {
        $pos = strrpos($laneId, '_lane');
        if ($pos === false) {
            throw new RuntimeException('Cannot derive lane user suffix: lane_id "' . $laneId . '" has no "_laneN" token.');
        }
        return substr($laneId, $pos);
    }

    /**
     * Takes the cross-process mutex that serializes test user provisioning.
     *
     * WHY flock: the lock is released by the OS when its owner dies, so a crashed worker can never
     * strand the mutex and block every future run - the same reasoning PortProbingTrait applies to
     * port reservations. Those helpers cannot be reused directly here: they are instance methods
     * built around a non-blocking per-port scan, whereas this is a single named mutex that must
     * WAIT, and setupUser() is static.
     *
     * WHY IT DEGRADES INSTEAD OF FAILING: if the lock cannot be taken within the deadline, the method
     * returns NULL and provisioning proceeds unserialized - exactly the behavior that existed before
     * this lock. A scenario must never fail because a mutex was busy; the worst outcome of skipping
     * it is the deadlock risk we already lived with, which the retry then covers.
     *
     * @return resource|null The open lock handle, or NULL if provisioning must proceed unlocked.
     */
    private static function acquireUserProvisioningLock(WorkbenchInterface $workbench)
    {
        // BdtPaths owns the folder layout; the degrade-instead-of-fail contract of this method is
        // preserved by turning its exception into the same warning the manual mkdir produced.
        try {
            $dir = BdtPaths::ensure($workbench->getInstallationPath(), BdtPaths::FOLDER_LOCKS);
        } catch (Throwable $e) {
            $workbench->getLogger()->warning('BDT: could not create the user provisioning lock directory - provisioning runs unserialized. ' . $e->getMessage());
            return null;
        }
        if (!is_dir($dir) && !@mkdir($dir, 0755, true) && !is_dir($dir)) {
            $workbench->getLogger()->warning('BDT: could not create the user provisioning lock directory ' . $dir . ' - provisioning runs unserialized.');
            return null;
        }

        // 'c' creates without truncating: the file is only a mutex, its bytes are diagnostic.
        $handle = @fopen($dir . DIRECTORY_SEPARATOR . 'user_provisioning.lock', 'c');
        if ($handle === false) {
            $workbench->getLogger()->warning('BDT: could not open the user provisioning lock - provisioning runs unserialized.');
            return null;
        }

        // Polled non-blocking acquisition rather than a plain blocking LOCK_EX, because PHP's blocking
        // flock has no timeout: a wedged holder would hang the lane until the worker timeout killed it.
        $deadline = microtime(true) + self::USER_PROVISIONING_LOCK_TIMEOUT_SECONDS;
        while (!flock($handle, LOCK_EX | LOCK_NB)) {
            if (microtime(true) >= $deadline) {
                fclose($handle);
                $workbench->getLogger()->warning(sprintf(
                    'BDT: user provisioning lock still held after %d s - proceeding unserialized.',
                    self::USER_PROVISIONING_LOCK_TIMEOUT_SECONDS
                ));
                return null;
            }
            usleep(100000);
        }

        @ftruncate($handle, 0);
        @fwrite($handle, sprintf('pid=%d acquired_at=%s%s', getmypid(), date('Y-m-d H:i:s'), PHP_EOL));
        @fflush($handle);
        return $handle;
    }

    /**
     * Reads the role UIDs currently assigned to a user.
     *
     * Exists so setupUser() can compare the wanted role set against the stored one before deciding
     * to write. A cheap indexed read replaces a delete-and-reinsert transaction in the common case
     * where consecutive scenarios of the same feature request identical roles.
     *
     * @param WorkbenchInterface $workbench
     * @param string $userId UID of the exface.Core.USER row.
     * @return string[] Role UIDs, unordered.
     */
    private static function readAssignedRoleUids(WorkbenchInterface $workbench, string $userId): array
    {
        $ds = DataSheetFactory::createFromObjectIdOrAlias($workbench, 'exface.Core.USER_ROLE_USERS');
        $ds->getFilters()->addConditionFromString('USER', $userId, ComparatorDataType::EQUALS);
        $col = $ds->getColumns()->addFromExpression('USER_ROLE');
        $ds->dataRead();
        return array_map('strval', $col->getValues(false));
    }

    /**
     * Compares two UID lists as unordered sets.
     *
     * Order and duplicates carry no meaning for a role assignment, so a plain array comparison would
     * report a difference whenever the data source returned the same roles in another order - and
     * every such false difference costs one deadlock-prone write.
     *
     * @param string[] $a
     * @param string[] $b
     */
    private static function isSameUidSet(array $a, array $b): bool
    {
        $a = array_unique(array_map('strval', $a));
        $b = array_unique(array_map('strval', $b));
        if (count($a) !== count($b)) {
            return false;
        }
        sort($a);
        sort($b);
        return $a === $b;
    }

    /**
     * Releases the provisioning mutex.
     *
     * Deliberately tolerates NULL so the caller's finally block needs no condition - acquisition is
     * allowed to fail, and the release path must not become a second failure mode. The file is never
     * unlinked: another process may hold it open, and removing a locked file underneath it is racy
     * on Windows.
     *
     * @param resource|null $handle Whatever acquireUserProvisioningLock() returned.
     */
    private static function releaseUserProvisioningLock($handle): void
    {
        if (is_resource($handle)) {
            @flock($handle, LOCK_UN);
            @fclose($handle);
        }
    }

    public function getEventDispatcher(): EventDispatcherInterface
    {
        return $this->eventDispatcher;
    }

    public static function resetUser(WorkbenchInterface $workbench): void
    {
        $config = $workbench->getApp('axenox.BDT')->getConfig();
        $dataSheet = DataSheetFactory::createFromObjectIdOrAlias($workbench, 'exface.Core.USER_ROLE_USERS');
        $dataSheet->getFilters()->addConditionFromString('USER__USERNAME', $config->getOption('TEST_USER.USERNAME'), ComparatorDataType::EQUALS);
        $dataSheet->dataDelete();
    }

    /**
     * Allows nodes to trigger navigation through the same pipeline
     * (DB/report logging + Mink visitPath + browser re-init) owned by the context.
     */
    public function setNavigator(callable $navigator): void
    {
        $this->navigator = $navigator;
    }

    /**
     * Navigate using the injected navigator.
     * This is intentionally not implemented here, because the context owns logging/reporting.
     */
    public function navigateToPageAlias(string $pageAlias): void
    {
        if (!$this->navigator) {
            throw new RuntimeException('Navigator callback is not configured on UI5Browser.');
        }
        ($this->navigator)($pageAlias);
    }

    /**
     * Gets the error detector instance that handles all error detection operations
     *
     * @return UI5ErrorDetector The error detector instance
     */
    public function getErrorDetector(): UI5ErrorDetector
    {
        return $this->errorDetector;
    }

    /**
     * Returns the locale information about session
     *
     * @return string
     */
    public function getLocale(): string
    {
        return $this->locale;
    }

    /**
     * Returns the role aliases that were applied to the test user at login time for
     * the current scenario.
     *
     * Nodes use this to build the role-aware cache keys required by
     * {@see DatabaseFormatter::hasTestedPage()} and {@see DatabaseFormatter::hasTestedWidget()}.
     *
     * @return string[] Sorted role alias array, or an empty array when no roles were set.
     */
    public function getCurrentRoles(): array
    {
        return $this->currentRoles;
    }

    /**
     * Stores the role aliases that were applied to the test user for the current scenario.
     *
     * Called by {@see UI5BrowserContext::iLogInToPage()} immediately after
     * {@see setupUser()} so that the roles are available to any node that needs them
     * without threading the role array through every method signature.
     *
     * @param string[] $roles Role aliases passed to the login step.
     * @return void
     */
    public function setCurrentRoles(array $roles): void
    {
        $this->currentRoles = $roles;
    }

    /**
     * Clears the XHR (XMLHttpRequest) monitoring log and resets error state
     *
     * This function performs two main cleanup tasks:
     * 1. Clears the XHR log array in the browser (window.exfXHRLog)
     * 2. Resets the internal error tracking state
     *
     * Use cases:
     * - Before starting a new test scenario
     * - After completing a test case
     * - When needing to reset monitoring state
     * - Before capturing new AJAX requests
     *
     * Note: This should be called before any new AJAX monitoring to ensure
     * clean state and prevent mixing logs from different test scenarios
     *
     * @return void
     * @see initializeXHRMonitoring() For the setup of the logging system
     */
    public function clearXHRLog(): void
    {
        $this->getSession()->evaluateScript(
            <<<JS

            if (window.exfXHRLog) {
                window.exfXHRLog.requests = [];
                window.exfXHRLog.lastRequest = [];
                window.exfXHRLog.errors = [];
            }
JS
        );
    }

    /**
     * Returns the Mink session used for browser interaction
     *
     * @return Session Current browser session
     */
    protected function getSession(): Session
    {
        return $this->session;
    }

    /**
     * Clears all widget highlights and debug labels from the UI
     *
     * This method removes:
     * - Outline and border styles from previously highlighted elements
     * - Global highlight indicators
     *
     * @throws \RuntimeException If script execution fails
     */
    public function clearWidgetHighlights(): void
    {

        try {
            $debugScript = <<<JS
            // Remove outline and border styles from highlighted elements    
            document.querySelectorAll('[style*="outline"]').forEach(el => { 
                el.style.outline = '';
                el.style.border = '';
            });

            // Call global highlight clearing function if it exists
            if (window.clearHighlight && typeof window.clearHighlight === 'function') {

                window.clearHighlight();
            }

            // Remove all debug labels
            document.querySelectorAll('.debug-highlight-label').forEach(label => {
                label.remove();
            });

            JS;

            $this->session->executeScript($debugScript);
        } catch (Exception $e) {
            // Throw a more specific RuntimeException with the original exception as the previous exception
            throw new RuntimeException(
                "Failed to clear widget highlights: " . $e->getMessage(),
                null,
                $e
            );
        }
    }

    /**
     * Handles wait operations before or after test steps
     *
     * This method ensures the UI is in a stable state by waiting for:
     * - AJAX requests to complete
     * - UI5 busy indicators to disappear
     *
     * @param bool $isAfterStep True if called after a step, false if before
     * @return void
     * @throws RuntimeException If wait operation fails
     */
    public function handleStepWaitOperations(bool $isAfterStep = true): void
    {
        try {
            if ($isAfterStep) {
                //$this->clearWidgetHighlights();
                // After step: Wait for all operations to complete
                $this->waitManager->waitForPendingOperations(true, true, true);

            } else {
                // Before step: Limited wait for UI stabilization
                $this->waitManager->waitForPendingOperations(false, true, false);
            }
        } catch (Throwable $e) {
            // Pass the original throwable as `previous`. Interpolating it into the message
            // only preserves its text - the object is lost, and with it every downstream
            // decision that depends on the exception TYPE (timeout classification, CDP
            // connection detection, Chrome recovery). Those all walk getPrevious().
            throw new RuntimeException(
                sprintf(
                    'Wait operation failed (%s step): %s',
                    $isAfterStep ? 'after' : 'before',
                    $e->getMessage()
                ),
                null,
                $e
            );
        }
    }

    public function getFocusStackForDebugging(): array
    {
        return $this->focusStack;
    }

    public function clearFocusStack(): void
    {
        $this->focusStack = []; // Focus stackini sıfırla

        // Opsiyonel: JavaScript ile de UI tarafında temizlik yapılabilir
        $this->session->executeScript('
        // if exist UI5 side focus clearing
        if (window.clearFocus) {
            window.clearFocus();
        }
    ');
    }

    /**
     * Highlights a widget with visual indicator for debugging purposes
     *
     * Adds a colored outline and label to the widget to make it visible
     * during test execution and debugging
     *
     * @param NodeElement $node Widget element to highlight
     * @param string $widgetType Type of the widget (used in label)
     * @param int $index Index number of the widget
     * @return void
     * @throws \RuntimeException If highlighting script execution fails
     */
    public function highlightWidget(NodeElement $node, string $widgetType, int $index): void
    {
        // Define color palette for different widget types
        $colors = [
            'DataTable' => '#4CAF50',  // Green
            'Dialog' => '#2196F3',     // Blue
            'Input' => '#FF9800',      // Orange
            'default' => '#9C27B0'     // Purple
        ];

        // Select color based on widget type, fallback to default
        $color = $colors[$widgetType] ?? $colors['default'];

        try {
            $highlightScript = sprintf(<<<JS
        (function() {
            const el = document.getElementById('%s');
            if (el) {
                el.style.outline = 'none';
                el.style.outline = '5px solid %s';
                el.style.outlineOffset = '4px';
                const existingLabel = el.querySelector('.debug-highlight-label');
                if (existingLabel) existingLabel.remove();
                const label = document.createElement('div');
                label.className = 'debug-highlight-label';
                label.style.cssText = `
                    position: absolute;
                    top: 0;
                    left: 0;
                    background: %s;
                    color: white;
                    padding: 2px;
                    font-size: 10px;
                    z-index: 9999;
                `;
                label.textContent = '%s #%d';
                el.appendChild(label);
                if (window.highlightElement && typeof window.highlightElement === 'function') {
                    window.highlightElement(el, '%s', '%s #%d');
                }
            }
        })();
        JS,
                $node->getAttribute('id'),
                $color,
                $color,
                $widgetType,
                $index + 1,
                $color,
                $widgetType,
                $index + 1
            );

            // Execute the highlighting script
            $this->session->executeScript($highlightScript);

        } catch (Throwable $e) {
            // Throw a more specific RuntimeException with context
            throw new RuntimeException(
                sprintf(
                    "Failed to highlight widget (Type: %s, Index: %d): %s",
                    $widgetType,
                    $index,
                    $e->getMessage()
                ),
                0,
                $e
            );
        }
    }

    /**
     * Displays the name of the current test case on the UI.
     *
     * This function creates a fixed position message div on the page
     * that shows the name of the test case being executed. The div
     * is styled to be visually distinct, with a selected colour background
     * and white text, making it easy to identify during test execution.
     *
     * The message div is created if it does not already exist, ensuring
     * that it does not duplicate if the function is called multiple times.
     *
     * @param string $testCaseName The name of the test case to display.
     * @return void
     */
    public function showTestCaseName(string $testCaseName): void
    {
        $this->session->executeScript(<<<JS
    (function() {
        // Check if the message div already exists
        let messageDiv = document.getElementById('testCaseNameDiv');
        
        // If it doesn't exist, create it
        if (!messageDiv) {
            messageDiv = document.createElement('div');
            messageDiv.id = 'testCaseNameDiv'; // Set an ID for future reference
            messageDiv.style.position = 'fixed';
            messageDiv.style.top = '10px';
            messageDiv.style.right = '10px';
            messageDiv.style.backgroundColor = '#4CAF50'; // Green
            messageDiv.style.color = 'white';
            messageDiv.style.padding = '10px';
            messageDiv.style.borderRadius = '5px';
            messageDiv.style.zIndex = '9999';
            document.body.appendChild(messageDiv); 
        }
        
        // Update the text of the message div
        messageDiv.innerText = '' + '{$testCaseName}';
    })();
JS
        );
    }

    /**
     * Displays step timing information on the UI.
     *
     * This function creates a fixed position message div on the page
     * that shows the timing information for test steps. It displays:
     * - Step start time when a step begins
     * - Both start and end times plus duration when a step completes
     *
     * The div is styled to be visually distinct from the test case name div,
     * positioned at the bottom right of the screen.
     *
     * @param string $stepName The name of the step being executed
     * @param bool $isStepStart Whether this is the start or end of the step
     * @param float|null $startTime The start time of the step (timestamp)
     * @return float Current timestamp (can be used as startTime for end call)
     */
    public function showStepTiming(string $stepName, bool $isStepStart = true, ?float $startTime = null): float
    {
        $currentTime = microtime(true);
        $formattedTime = date('H:i:s', (int)$currentTime) . '.' . substr(number_format($currentTime - (int)$currentTime, 3), 2);

        if ($isStepStart) {
            // For step start, just show the start time
            $message = "Started at: {$formattedTime}";
        } else {
            // For step end, show start, end and duration
            $duration = $currentTime - $startTime;
            $formattedStartTime = date('H:i:s', (int)$startTime) . '.' . substr(number_format($startTime - (int)$startTime, 3), 2);
            $message = "Started: {$formattedStartTime}<br>Ended: {$formattedTime}<br>Duration: " . number_format($duration, 3) . " sec";
        }

        // Convert PHP boolean to JavaScript boolean string
        $isStepStartJS = $isStepStart ? 'false' : 'true';

        $this->session->executeScript(<<<JS
    (function() {
        // Check if the timing div already exists
        let timingDiv = document.getElementById('stepTimingDiv');
        
        // If it doesn't exist, create it
        if (!timingDiv) {
            timingDiv = document.createElement('div');
            timingDiv.id = 'stepTimingDiv';
            timingDiv.style.position = 'fixed';
            timingDiv.style.bottom = '10px';
            timingDiv.style.right = '10px';
            timingDiv.style.backgroundColor = '#2196F3'; // Blue color to distinguish from test case name
            timingDiv.style.color = 'white';
            timingDiv.style.padding = '10px';
            timingDiv.style.borderRadius = '5px';
            timingDiv.style.zIndex = '9999';
            timingDiv.style.fontFamily = 'monospace'; // For better readability of times
            timingDiv.style.fontSize = '14px';
            timingDiv.style.maxWidth = '300px'; 
            timingDiv.style.pointerEvents = 'none'; // Able to clicks
            
            

            document.body.appendChild(timingDiv);
        }
        
        // Updading the text of the timing div
        timingDiv.innerHTML = '<strong>Step: {$stepName}</strong><br>' + '{$message}';
        
        // If this is the end of the step, wait 1 second and then update the div
        if ({$isStepStartJS}) {
            setTimeout(function() {
                timingDiv.innerHTML += '<br><em>Continuing in 1s...</em>';
            }, 0);
            
            // Wait 0,5 seconds before next step
            setTimeout(function() {
                // You can clear or update the message here if needed
            }, 500);
        }
    })();
JS
        );

        // Return current time so it can be used as startTime for the end call
        return $currentTime;
    }

    /**
     * Helper function to get widget location description
     * Used to provide context about where in the UI a widget is located
     *
     * @param NodeElement $widget The widget to get location for
     * @return string Human-readable location description
     */
    public function getWidgetLocation(NodeElement $widget): string
    {
        $parent = $widget->find('xpath', './ancestor::*[contains(@class, "sapMPage") or contains(@class, "sapMPopup")][1]');
        if ($parent) {
            $title = $parent->find('css', '.sapMTitle');
            if ($title) {
                return "in " . trim($title->getText());
            }
        }
        return "in page";
    }

    /**
     * Sets focus on a node and maintains a focus stack
     * Used to track which elements have focus during test execution
     *
     * @param NodeElement|FacadeNodeInterface $node The element to focus
     * @return void
     */
    public function focus($node): void
    {
        switch (true) {
            case $node instanceof FacadeNodeInterface:
                // everything is finde
                break;
            case $node instanceof NodeElement:
                $node = new GenericHtmlNode($node, $this->getSession(), $this);
                break;
            default:
                throw new InvalidArgumentException('Cannot focus on "' . gettype($node) . '": expecting Mink NodeElement or FacadeNodeInterface');
        }
        $top = end($this->focusStack);
        if ($top !== $node) {
            $this->focusStack[] = $node;
        }
    }

    /**
     * Gets current URL with hash fragment
     * This ensures we get the complete URL including UI5 routing information
     *
     * @return string Complete URL including hash
     */
    public function getCurrentUrlWithHash(): string
    {
        return $this->session->evaluateScript('
        (function() {
            var baseUrl = window.location.href;
            var hash = window.location.hash;
            
            // Check for UI5 specific hash handling
            if (typeof sap !== "undefined" && 
                sap.ui && 
                sap.ui.core && 
                sap.ui.core.routing && 
                sap.ui.core.routing.HashChanger) {
                
                try {
                    // Get hash from UI5 router
                    hash = "#" + sap.ui.core.routing.HashChanger.getInstance().getHash();
                } catch(e) {
                    // Fallback to browser hash if UI5 router not available
                    console.warn("UI5 router not available:", e);
                }
            }
            
            // Ensure we don\'t duplicate the hash
            baseUrl = baseUrl.split("#")[0];
            
            return baseUrl + (hash || "");
        })();
    ');
    }

    /**
     * Initializes XHR and AJAX Request Monitoring System
     *
     * This function sets up a comprehensive monitoring system for all network requests by:
     * - Creating a wrapper around XMLHttpRequest without modifying its core functionality (Uses wrapper pattern instead of modifying original XHR)
     * - Monitoring jQuery AJAX calls through $.ajaxSetup
     * - Tracking all fetch API requests , Catches HTTP errors (400, 500 etc.)
     *
     * Features:
     * - Captures all network activity including status codes and responses
     * - Detects HTTP errors (400, 500 etc.) and UI5 specific errors
     * - Logs detailed request information (timestamps, duration, responses)
     * - Stores logs separately in window.exfXHRLog without affecting application
     *
     * Use Cases:
     * - Test automation error detection
     * - Network request debugging
     * - Error state capturing
     * - Automatic error logging
     *
     * @method initializeXHRMonitoring
     * @return void
     * @throws \RuntimeException if XHR monitoring initialization fails
     */
    public function initializeXHRMonitoring(): void
    {
        $this->getSession()->evaluateScript(
            <<<JS
            (function() {
                // Global error manager
                window.exfErrorManager = {
                    processedErrors: new Set(),
                    addError: function(error) {
                        const hash = this.generateErrorHash(error);
                        if (!this.processedErrors.has(hash)) {
                            this.processedErrors.add(hash);
                            console.error('Error logged:', error);
                        }
                    },
                    generateErrorHash: function(error) {
                        const url = (error.url || '').replace(/[?&][^=]*=[^&]*/g, '');
                        return `\${error.type}|\${error.status}|\${url}`;
                    }
                };

                // XHR logging object with improved error handling
                window.exfXHRLog = {
                    requests: [],
                    errors: [],
                    addRequest: function(request) {
                        request.timestamp = new Date().toISOString();
                        this.requests.push(request);
                        
                        if (request.status >= 400) {
                            const error = {
                                type: 'Network',
                                status: request.status,
                                url: request.url,
                                message: request.statusText,
                                request: request,
                                response: request.response,
                                timestamp: request.timestamp
                            };
                            
                            this.errors.push(error);
                        }
                    },
                    resetErrors: function() {
                        this.errors = [];
                    },
                    resetRequests: function() {
                        this.requests = [];
                    }
                };

                // Enhance jQuery AJAX monitoring
                if (typeof jQuery !== 'undefined') {
                    const originalAjax = jQuery.ajax;
                    jQuery.ajax = function(options) {
                        const startTime = Date.now();
                        const originalComplete = options.complete;
                        
                        options.complete = function(jqXHR, textStatus) {
                            try {
                                const request = {
                                    url: jqXHR.responseURL || options.url,
                                    method: options.type || 'GET',
                                    status: jqXHR.status,
                                    statusText: jqXHR.statusText,
                                    response: jqXHR.responseText,
                                    duration: Date.now() - startTime
                                };
                                
                                window.exfXHRLog.addRequest(request);
                                
                                if (originalComplete) {
                                    originalComplete.apply(this, arguments);
                                }
                            } catch (e) {
                                window.exfErrorManager.addError({
                                    type: 'JSError',
                                    message: e.message,
                                    stack: e.stack
                                });
                            }
                        };
                        
                        return originalAjax.apply(this, arguments);
                    };
                }

                // Enhanced fetch API monitoring
                if (typeof window.fetch === 'function') {
                    const originalFetch = window.fetch;
                    window.fetch = async function(input, init) {
                        const startTime = Date.now();
                        const url = typeof input === 'string' ? input : input.url;
                        const method = init?.method || 'GET';
                        
                        try {
                            const response = await originalFetch.apply(this, arguments);
                            const clone = response.clone();
                            const responseText = await clone.text();
                            
                            window.exfXHRLog.addRequest({
                                url: url,
                                method: method,
                                status: response.status,
                                statusText: response.statusText,
                                response: responseText,
                                duration: Date.now() - startTime
                            });
                            
                            return response;
                        } catch (error) {
                            const errorDetails = {
                                url: url,
                                method: method,
                                status: 0,
                                statusText: error.message,
                                error: error.toString(),
                                duration: Date.now() - startTime
                            };
                            
                            window.exfXHRLog.addRequest(errorDetails);
                            window.exfErrorManager.addError({
                                type: 'FetchError',
                                message: error.message,
                                url: url
                            });
                            
                            throw error;
                        }
                    };
                }

                console.log('Enhanced XHR monitoring initialized successfully');
            })();
JS
        );

        // Verify initialization
        $isInitialized = $this->getSession()->evaluateScript(
            'return typeof window.exfXHRLog !== "undefined" && typeof window.exfXHRLog.addRequest === "function"'
        );

        if (!$isInitialized) {
            throw new \RuntimeException('XHR monitoring initialization failed');
        }
    }

    /**
     * Finds an input element by its associated label caption in a UI5 application
     *
     * This function performs a hierarchical search to find input elements:
     * 1. First finds the label element with matching caption
     * 2. Then locates the corresponding input through the label's 'for' attribute
     * 3. Handles different UI5 input structures and nested elements
     *
     * @param string $caption The label text to search for
     * @param NodeElement|null $parent Optional parent element to search within
     * @return NodeElement|null The found input element or null if not found
     */
    public function findInputByCaption(string $caption, NodeElement $parent = null): ?NodeElement
    {
        // Get the page or use provided parent element as search context
        $page = $this->getPage();
        $input = null;
        $context = ($parent ?? $page);

        // Use a descendant selector (space instead of '>') to find 'bdi' anywhere inside the label.
        // This handles UI5 updates that inject extra wrapper divs like '.sapMLabelInner'.
        $labelBdis = $context->findAll('css', 'label.sapMLabel bdi');

        foreach ($labelBdis as $labelBdi) {
            // Compare the trimmed text to avoid issues with hidden whitespace or newlines in UI5 labels
            if (trim($labelBdi->getText()) === $caption) {
                try {
                    // Use XPath to climb up the DOM tree and find the nearest 'label' ancestor.
                    // This is much safer than chained getParent() calls which break on structural changes.
                    $labelElement = $labelBdi->find('xpath', './ancestor::label');

                    if (!$labelElement) {
                        continue;
                    }

                    // UI5 labels use the 'for' attribute to point to the input's ID (usually the -inner ID).
                    $labelFor = $labelElement->getAttribute('for');
                    if (!$labelFor) {
                        continue;
                    }

                    // Attempt 1: Try to find the input directly by the ID provided in the 'for' attribute.
                    $input = $context->findById($labelFor);

                    // Attempt 2: If not found directly, the 'for' ID might point to a container.
                    // Look for the actual interactive input element within that container.
                    if (!$input) {
                        $container = $context->findById($labelFor);
                        if ($container) {
                            $input = $container->find('css', 'input.sapMInputBaseInner, input');
                        }
                    }

                    // Break the loop once the correct input is identified
                    if ($input) {
                        break;
                    }
                } catch (Exception $e) {
                    continue;
                }
            }
        }

        return $input;
    }

    /**
     * Returns the current page object from the Mink session
     *
     * @return DocumentElement Current page object
     */
    public function getPage()
    {
        return $this->session->getPage();
    }

    /**
     * Finds a column by its caption text
     *
     * @param string $caption The column caption to search for
     * @param NodeElement|FacadeNodeInterface|null $parent Optional parent element to search within
     * @return NodeElement|null The found column element or null if not found
     */
    public function findColumnByCaption(string $caption, $parent = null): ?NodeElement
    {
        // FacadeNodeInterface ise NodeElement'e dönüştür
        if ($parent instanceof FacadeNodeInterface) {
            // UI5AbstractNode sınıfı getNodeElement() metodunu kullanıyor
            $parent = $parent->getNodeElement();
        }

        $columnHeadings = ($parent ?? $this->getPage())->findAll('css', '.sapUiTableHeaderCell');

        // Iterate through found column headings to locate matching one
        foreach ($columnHeadings as $columnHeading) {
            if ($columnHeading->getText() === $caption && $columnHeading->isVisible()) {
                // Return the column element
                return $columnHeading;
            }
        }
        return null;
    }

    /**
     * Navigates to a specific tab by caption
     * If the tab is not already active, clicks it to activate
     *
     * @param string $caption Tab caption to find and navigate to
     * @param NodeElement|null $parent Optional parent element to search within
     * @param int $attempts Number of attempts to find the tab
     * @return NodeElement|null The found tab element or null if not found
     * @throws AssertionFailedError If tab cannot be found
     */
    public function goToTab(string $caption, NodeElement $parent = null, int $attempts = 1): ?NodeElement
    {
        $tab = $this->findTabByCaption($caption, $parent);
        if ($tab === null && $attempts > 1) {
            // Try again after waiting for UI updates
            $attempts--;
            return $this->goToTab($caption, $parent, $attempts);
        }
        Assert::assertNotNull($tab, 'Cannot find tab "' . $caption . '"');
        // If the tab is not active, click on it to switch to the right authenticator
        if (!$tab->hasClass('sapMITBSelected')) {
            $tab->click();
        }
        return $tab;
    }

    /**
     * Finds a tab element by its caption text
     *
     * @param string $caption The tab caption to search for
     * @param NodeElement|null $parent Optional parent element to search within
     * @return NodeElement|null The found tab element or null if not found
     */
    public function findTabByCaption(string $caption, NodeElement $parent = null): ?NodeElement
    {
        $selectors = ['.sapMITBItem .sapMITHTextContent ', '.sapUxAPAnchorBarScrollContainer > div > button.sapMBtn > span > span > bdi'];
        // Find all tab heading elements
        $tabHeadings = ($parent ?? $this->getPage())->findAll('css', implode(',', $selectors));

        // Iterate through found tab headings to locate matching one
        foreach ($tabHeadings as $tabHeading) {
            if ($tabHeading->getText() === $caption && $tabHeading->isVisible()) {
                // Return the parent tab element (navigate up to the actual tab container)
                return $tabHeading->getParent()->getParent()->getParent();
            }
        }
        return null;
    }

    /**
     * Finds a button element by its caption text
     *
     * @param string $caption The button text to search for
     * @param NodeElement|null $parent Optional parent element to search within
     * @return NodeElement|null The found button element or null if not found
     */
    public function findButtonByCaption(string $caption, NodeElement $parent = null): ?NodeElement
    {
        $page = $this->getPage();
        // Find all button elements with BDI text container
        $labelBdis = ($parent ?? $page)->findAll('css', 'button.sapMBtn > span > span > bdi');
        // Check each button's text content
        foreach ($labelBdis as $labelBdi) {
            if ($labelBdi->getText() !== $caption) {
                continue;
            }
            // Navigate up to the actual button element
            $button = $labelBdi->getParent()->getParent()->getParent();
            // WHY AN INVISIBLE MATCH IS SKIPPED INSTEAD OF ASSERTED ON: the method used to abort the
            // whole search with "Button ... is not visible" as soon as ANY match was invisible. A page
            // regularly holds several elements for the same caption (a hidden template, a button of a
            // collapsed toolbar), so the first, unusable one hid the visible one behind it - and it
            // made every caller unable to fall back to the toolbar overflow, because an exception is
            // not a "not found". Returning null lets the caller decide what to do next.
            if ($button->isVisible()) {
                return $button;
            }
        }
        return null;
    }

    /**
     * Finds a visible button inside the given scope whose text or tooltip matches the caption.
     *
     * WHY IT EXISTS: the caption match used by the click steps ("contains, case insensitive") was
     * written out three times - once for the focused widget, once for the page and once more for the
     * table variant - and the copies had already drifted apart (only one of them looked at the title
     * attribute). One implementation means the overflow fallback matches captions exactly the way the
     * regular search does, which is the whole point of a fallback.
     *
     * WHY AN EXACT MATCH WINS OVER A LOOSE ONE, AND WHY THE SCAN CONTINUES TO FIND IT: a substring
     * match makes "Speichern" match "Speichern und Schließen" as well, so whichever of the two the
     * facade happens to render first would be clicked. Returning on the first loose hit therefore made
     * the outcome depend on DOM order rather than on what the scenario asked for. The loose candidate
     * is remembered instead and only used once the whole scope is known to hold no exact match.
     *
     * WHY IT SKIPS INVISIBLE CANDIDATES INSTEAD OF RETURNING THEM: an invisible button cannot be
     * clicked, and returning it would end the search before the visible twin - or the overflow entry -
     * is ever considered.
     *
     * @param \Behat\Mink\Element\TraversableElement $scope
     * @param string $caption
     * @return NodeElement|null
     */
    public function findButtonInScopeByCaption($scope, string $caption): ?NodeElement
    {
        $needle = trim($caption);
        $looseMatch = null;

        foreach ($scope->findAll('css', 'button') as $btn) {
            if (! $btn->isVisible()) {
                continue;
            }

            // Read the text ONCE: every accessor on a Mink element is a separate synchronous CDP
            // round trip, and this loop runs over every button of the scope - page wide in the
            // fallback of the click steps.
            $text = trim($btn->getText());
            if ($text === $needle) {
                return $btn;
            }

            // A candidate is enough: skip the tooltip round trip for every further button once one
            // loose match is known - the scan from here on only looks for an exact match.
            if ($looseMatch !== null) {
                continue;
            }
            if (stripos($text, $needle) !== false) {
                $looseMatch = $btn;
                continue;
            }
            $title = $btn->getAttribute('title');
            if ($title !== null && stripos($title, $needle) !== false) {
                $looseMatch = $btn;
            }
        }

        return $looseMatch;
    }

    /**
     * Finds the latest downloaded XLSX file
     *
     * @return string|null Full path of the downloaded file
     */
    public function findLatestXlsxFile(): ?string
    {
        $config = $this->getWorkbench()->getApp('axenox.BDT')->getConfig();
        $downloadDir = $config->getOption('TEST_DOWNLOADS.DIRECTORY_WINDOWS');

        // Find XLSX files modified in the last 2 minutes 
        $twoMinutesAgo = time() - 120;

        $files = scandir($downloadDir, SCANDIR_SORT_DESCENDING);
        foreach ($files as $file) {
            $filePath = $downloadDir . DIRECTORY_SEPARATOR . $file;

            if (
                is_file($filePath) &&
                strtolower(pathinfo($file, PATHINFO_EXTENSION)) === 'xlsx' &&
                filemtime($filePath) >= $twoMinutesAgo
            ) {
                return $filePath;
            }
        }

        return null;
    }

    /**
     * Returns the workbench instance for the application
     *
     * @return Workbench Application workbench
     */
    public function getWorkbench()
    {
        return $this->workbench;
    }

    /**
     * Finds widgets of the given type strictly inside the given container node - never outside it.
     *
     * WHY: assertions like "it has :number widget of type" are only meaningful within the container a
     * previous step focused on. findWidgetNodes() cannot serve them, because it deliberately falls back
     * to a page-wide search when the focused scope yields nothing - which silently turns "this dialog
     * contains no inputs" into "the page contains twelve inputs" and lets the assertion pass or fail for
     * the wrong reason. This method has no fallback: an empty result means the container really is empty.
     *
     * @param FacadeNodeInterface $containerNode Node to search within
     * @param string $widgetType
     * @param int $number Number of widgets to wait for before asserting
     * @param int $timeoutInSeconds
     * @return FacadeNodeInterface[]
     * @throws Exception
     */
    public function findWidgetNodesInNode(FacadeNodeInterface $containerNode, string $widgetType, int $number = 1, int $timeoutInSeconds = 10): array
    {
        $this->waitManager->waitForPendingOperations(true, true, true);

        $cssSelector = $this->buildCssSelectorForWidgetType($widgetType);

        // The pre-wait is page-wide on purpose: waitForDOMElements() evaluates its jQuery selector against
        // the document and cannot be restricted to a single element. It is only used to avoid asserting
        // against a DOM that has not finished rendering - the authoritative count is the scoped search
        // below. Waiting for 0 elements would be pointless, so it is skipped for a "has no widgets" check.
        if ($timeoutInSeconds > 0 && $number > 0) {
            $this->waitManager->waitForDOMElements($cssSelector, $number, $timeoutInSeconds);
        }

        return $this->findWidgetNodesInScope($this->resolveContainerElement($containerNode), $widgetType, null, $cssSelector);
    }

    /**
     * Resolves the DOM element of a container that a scoped search must not leave.
     *
     * WHY: unlike findWidgetNodes(), a scoped search has no page-wide fallback - so when the container
     * has meanwhile disappeared from the DOM (a dialog closed by a previous step, a re-rendered
     * toolbar), Mink aborts with a raw "Tag matching xpath //DIV[@id=...] not found". That message
     * names an internal element id and sends whoever reads it looking for a rendering bug, while the
     * real problem is that the step is looking at something that is no longer there.
     *
     * @param FacadeNodeInterface $containerNode
     * @return ElementInterface
     * @throws RuntimeException If the container is no longer part of the DOM
     */
    protected function resolveContainerElement(FacadeNodeInterface $containerNode): ElementInterface
    {
        try {
            $el = $containerNode->getNodeElement();
            $valid = $el !== null && $el->isValid();
        } catch (Throwable $e) {
            $valid = false;
        }

        if ($valid !== true) {
            throw new RuntimeException(
                'Cannot search inside the "' . $containerNode->getWidgetType() . '" currently in focus: '
                . 'it is no longer part of the page - it was probably closed or re-rendered by an earlier step. '
                . 'Focus a widget that is still visible (e.g. "I look at table 1") before this step.'
            );
        }

        return $el;
    }

    /**
     * Builds the CSS selector for a widget type INCLUDING every subtype currently rendered.
     *
     * WHY: the UI5 facade writes exactly one `.exfw-<WidgetType>` class per widget and that class
     * always holds the CONCRETE type. A CSS class selector matches whole class tokens, so
     * `.exfw-Input` never matches `.exfw-InputComboTable`. Every step that addresses widgets by
     * type would therefore ignore all specialised variants, even though the metamodel derives them
     * from the requested type. This method restores the metamodel semantics by collecting the
     * widget types actually present in the DOM and keeping the ones whose widget class is - or
     * extends - the requested one.
     *
     * The type discovery is intentionally page-wide even when the caller searches inside a
     * container afterwards: an extra type in the selector can only ever match zero additional
     * elements within a narrower scope, whereas a scoped discovery would cost one CDP round trip
     * per element.
     *
     * @param string $widgetType The widget type requested by the test step
     * @return string A CSS selector, e.g. ".exfw-Input, .exfw-InputComboTable"
     */
    public function buildCssSelectorForWidgetType(string $widgetType): string
    {
        $baseSelector = '.exfw-' . $widgetType;

        $typesFound = $this->session->evaluateScript('
            (function(){
                var types = {};
                document.querySelectorAll(\'[class*="exfw-"]\').forEach(function(el){
                    el.classList.forEach(function(cls){
                        if (cls.indexOf("exfw-") === 0) {
                            types[cls.substring(5)] = true;
                        }
                    });
                });
                return Object.keys(types).join(",");
            })();
        ');

        if (!is_string($typesFound) || $typesFound === '') {
            return $baseSelector;
        }

        $selectors = [];
        foreach (explode(',', $typesFound) as $typeFound) {
            if (UI5FacadeNodeFactory::isWidgetTypeDerivedFrom($typeFound, $widgetType)) {
                $selectors[] = '.exfw-' . $typeFound;
            }
        }

        // Never hand back an empty selector: when nothing has matched yet - e.g. the dialog is still
        // being rendered - the caller must still be able to WAIT for the plain type selector.
        return empty($selectors) ? $baseSelector : implode(', ', $selectors);
    }

    /**
     * Converts every visible widget of the given type inside the given DOM scope into a facade node.
     *
     * WHY: a scoped search (inside a container) and a page-wide search only differ by the element they
     * start from - selector, visibility filter, node creation and object filtering are identical. Keeping
     * that shared part here means the object alias filter is implemented once and cannot drift between
     * the two entry points.
     *
     * @param ElementInterface $scope Document or DOM element to search within
     * @param string $widgetType
     * @param string|null $caption Optional meta object alias to restrict the result to
     * @param string|null $cssSelector Pre-resolved selector - pass it when the caller already built one,
     *        so the DOM type scan is not repeated over CDP for the same step
     * @return FacadeNodeInterface[]
     */
    protected function findWidgetNodesInScope(ElementInterface $scope, string $widgetType, ?string $caption = null, ?string $cssSelector = null): array
    {
        // Identify the scope element ONCE instead of per match. A DocumentElement has no id and can
        // never be matched by an `.exfw-*` selector anyway, so a page-wide search skips the self-check
        // below entirely and pays nothing for it - which matters, because every attribute read here is
        // a separate synchronous CDP round trip.
        $scopeId = $scope instanceof NodeElement ? (string)$scope->getAttribute('id') : '';

        $nodes = [];
        foreach ($scope->findAll('css', $cssSelector) as $nodeEl) {
            if (!$nodeEl->isVisible()) {
                continue;
            }
            // Skip the scope element itself, so this really returns the widgets INSIDE the scope.
            // WHY THIS IS NEEDED: Mink converts a CSS selector into an XPath beginning with
            // `descendant-or-self::`, so a scoped search for the very widget type the scope element
            // has matches that scope element again. The scoped result of findWidgetNodes() was
            // therefore never empty for such a search, its page-wide fallback never ran, and looking
            // at table 2 right after table 1 could only ever see the one table already in focus.
            // WHY THE ID AND NOT THE XPATH: Mink builds the XPath of a found element on its own and
            // does not necessarily format it the way the scope element's XPath was built, so comparing
            // the two strings is unreliable. Every UI5 widget root carries a stable DOM id.
            if ($scopeId !== '' && $nodeEl->getAttribute('id') === $scopeId) {
                continue;
            }
            // Derive the node class from the element's own `.exfw-<Type>` class, NOT from the requested
            // type. WHY: the selector matches subtypes now, so passing $widgetType here would wrap an
            // InputComboTable element into a plain UI5InputNode and silently lose its combo behaviour
            // for every step that reuses the returned nodes.
            $nodes[] = UI5FacadeNodeFactory::createFromNodeElement($nodeEl, $this->getSession(), $this);
        }

        return $this->filterNodesByName($nodes, $caption);
    }

    /**
     * Reduces a set of widget nodes to those matching the given name - a caption or a meta object.
     *
     * WHY both: the `with ":name"` part of the widget steps is written by hand and authors use whatever
     * identifies the widget in the app in front of them - the dialog title ("Materialbedarfsliste Seile
     * erstellen") just as often as the object behind a table ("Materialbedarfsliste"). Accepting only the
     * object alias made every scenario using the other notation return zero matches, which reads like
     * "the widget is not on the page" instead of "you named it differently than this filter expects".
     *
     * WHY the metamodel and not the DOM: neither caption nor alias is rendered anywhere reliable, so
     * matching against visible text would let a caption or a table cell that happens to contain the same
     * words pass as a match - exactly the kind of false green this filter exists to prevent.
     *
     * The comparison is case insensitive and accepts the object alias in both notations - fully qualified
     * ("my.App.CUSTOMER") and short ("CUSTOMER") - because the namespace is noise in most steps.
     *
     * @param FacadeNodeInterface[] $nodes
     * @param string|null $name Null or empty disables filtering and returns the input unchanged
     * @return FacadeNodeInterface[]
     */
    public function filterNodesByName(array $nodes, ?string $name): array
    {
        // Resolving the widget of every node hits the page model, so skip the whole loop when there is
        // nothing to filter by - which is the case for the majority of steps.
        if ($name === null || $name === '') {
            return $nodes;
        }

        $name = trim($name);
        $filtered = [];
        foreach ($nodes as $node) {
            // A node whose widget cannot be resolved from the page model cannot be proven to match, so it
            // counts as a non-match. WHY not let it bubble up: one unrelated widget on the page would
            // otherwise turn a filtered assertion into a fatal error instead of a clean count mismatch.
            try {
                $widget = $node->getWidget();
                $object = $widget->getMetaObject();
            } catch (Throwable $e) {
                continue;
            }

            $candidates = [
                $widget->getCaption(),
                $object->getName(),
                $object->getAlias(),
                $object->getAliasWithNamespace()
            ];

            foreach ($candidates as $candidate) {
                if ($candidate !== null && $candidate !== '' && strcasecmp(trim($candidate), $name) === 0) {
                    $filtered[] = $node;
                    break;
                }
            }
        }

        return $filtered;
    }

    /**
     *
     * @param string $pageUrl
     * @param string|null $widgetId
     * @param string|null $assertWidgetType
     * @return WidgetInterface
     */
    protected function getWidget(string $pageUrl, string $widgetId = null, string $assertWidgetType = null): WidgetInterface
    {
        $page = UiPageFactory::createFromModel($this->getWorkbench(), $pageUrl);
        $widget = $widgetId !== null ? $page->getWidget($widgetId) : $page->getWidgetRoot();
        if ($assertWidgetType !== null) {
            Assert::assertEquals($assertWidgetType, $widget->getType(), 'Widget ' . $widgetId . ' is not of expected type "' . $assertWidgetType . '"!');
        }
        return $widget;
    }

    /**
     * Finds the widgets a step can use as a search scope when it only knows the widget's NAME.
     *
     * WHY: steps like "I see button :buttonText at the :tableName" name the container the way the
     * test author sees it in the app - the table caption or the object behind it - but they never
     * name its widget TYPE. findWidgetNodes() can already filter by name, yet it insists on a type,
     * so every such step either had to hard-wire one type (and then miss dialogs and panels) or -
     * as was the case until now - drop the name and search the whole page, which lets a button
     * belonging to a completely different widget satisfy the assertion.
     *
     * WHY these two types in this order: `Data` covers every table/list variant, which is what
     * "at the ..." refers to in practice, and `Container` covers dialogs, panels and forms as a
     * fallback. Both are resolved through the metamodel hierarchy by buildCssSelectorForWidgetType(),
     * so concrete subtypes (DataTable, DataTableResponsive, Dialog, Form, ...) are included.
     *
     * WHY the timeout is dropped after the first pass: the wait inside findWidgetNodes() blocks
     * until at least one widget of that type exists. Keeping the timeout for the fallback pass
     * would burn it a second time on every page that simply has no widget of that type.
     *
     * @param string $name Caption, object name or object alias of the widget to use as scope
     * @param int $timeoutInSeconds Maximum time to wait for the widgets to appear
     * @param string[] $widgetTypes Base widget types to look in, in order of preference
     * @return FacadeNodeInterface[] Empty when no widget matches the name
     * @throws Exception
     */
    public function findWidgetNodesByName(string $name, int $timeoutInSeconds = 10, array $widgetTypes = ['Data', 'Container']): array
    {
        foreach ($widgetTypes as $widgetType) {
            $nodes = $this->findWidgetNodes($widgetType, $timeoutInSeconds, $name);
            if (!empty($nodes)) {
                return $nodes;
            }
            $timeoutInSeconds = 0;
        }

        return [];
    }

    /**
     * Finds widgets of the given type in the currently focused scope, falling back to the whole page.
     *
     * WHY the fallback: most steps run without an explicit focus (or right after a navigation reset the
     * focus stack), and a page-wide result is the useful answer there. Steps that must NOT leave the
     * container - like "it has :number widget of type" - deliberately use findWidgetNodesInNode()
     * instead, which has no fallback.
     *
     * @param string $widgetType
     * @param int $timeoutInSeconds
     * @param string|null $caption Optional caption of the widget
     * @return FacadeNodeInterface[]
     * @throws Exception
     */
    public function findWidgetNodes(string $widgetType, int $timeoutInSeconds = 10, ?string $caption = null): array
    {
        // Let the UI settle BEFORE scanning the DOM for widget types - a subtype that is still being
        // rendered would otherwise be missing from the selector.
        $this->waitManager->waitForPendingOperations(true, true, true);

        if ($timeoutInSeconds > 0) {
            $this->waitManager->waitForDOMElements(
                $this->buildCssSelectorForWidgetType($widgetType),
                1,
                $timeoutInSeconds
            );
        }

        // Resolve the selector once more AFTER the wait: a subtype may have entered the DOM only during
        // that wait and would otherwise be absent from the selector used for the actual search.
        $cssSelector = $this->buildCssSelectorForWidgetType($widgetType);

        $nodes = $this->findWidgetNodesInScope($this->getFocusedNode()->getNodeElement(), $widgetType, $caption, $cssSelector);
        if (empty($nodes)) {
            $nodes = $this->findWidgetNodesInScope($this->getPage(), $widgetType, $caption, $cssSelector);
        }

        return $nodes;
    }

    /**
     * Gets the currently focused node
     * Returns the top element of the focus stack
     *
     * @return FacadeNodeInterface The focused element or null if none focused
     */
    public function getFocusedNode(): FacadeNodeInterface
    {
        $this->pruneDeadFocus();
        if (empty($this->focusStack)) {
            return new UI5PageNode($this->getPageAliasFromCurrentUrl(), $this->getSession(), $this);
        }
        $top = end($this->focusStack);
        return $top;
    }

    /**
     * Discards focus entries whose DOM element is no longer part of the page.
     *
     * WHY THIS EXISTS: the focus stack outlives the DOM. Nothing pops a dialog off the stack when
     * it closes - there is no "unfocus" step and no close event - so a dialog focused by
     * "I see 1 widget of type Dialog" is still the top of the stack after "Save" removed it from
     * the page. Every reader of the stack then hands that dead element to the driver, which aborts
     * with a raw "Tag matching xpath //DIV[@id=..._Dialog] not found". That message names an
     * internal element id and sends whoever reads it looking for a rendering bug, while the real
     * problem is that the framework is still looking at something that no longer exists.
     *
     * WHY IT IS DONE ON READ AND NOT ON CLOSE: a widget can leave the DOM in many ways - a dialog
     * closed by a save, by cancel, by ESC, a toolbar re-rendered after a refresh, a table replaced
     * by navigation. Detecting each of those would mean a growing list of special cases that is
     * wrong the moment a new one appears. Checking validity where the stack is consumed covers all
     * of them with one rule.
     */
    private function pruneDeadFocus(): void
    {
        while (! empty($this->focusStack)) {
            try {
                if (end($this->focusStack)->getNodeElement()->isValid()) {
                    return;
                }
            } catch (Throwable $e) {
                // A stale handle throws instead of reporting itself as invalid - same conclusion
            }
            array_pop($this->focusStack);
        }
    }

    /**
     * Returns the "logical" UI page alias from the current URL.
     *
     * WHY the fragment is inspected at all:
     * - Some pages use hash-based routing (SPA style). In that case the real target page alias lives
     *   in the URL fragment (#/...), not in the ".html" part.
     *
     * WHY the fragment is not trusted blindly:
     * - The UI5 facade uses the very same fragment for WIDGET routes, not only for page routes. When
     *   a button opens a dialog, the fragment becomes "#/<pageAlias>.<dialogWidgetId>/<data>". That
     *   first segment looks exactly like an alias, but it addresses a widget inside the page that is
     *   already open. Returning it made every caller of getPageCurrent() ask the model for a page
     *   that cannot exist, which surfaced as "UI Page with alias ... not found!" although the dialog
     *   had opened correctly.
     * - A widget route is recognisable without guessing: it always starts with the alias of the page
     *   loaded from the ".html" file, followed by a dot. A real sub-page route is a different alias
     *   and never carries that prefix. So whenever the prefix is present, we are still on the
     *   ".html" page itself.
     *
     * Examples:
     *   /nbr.onelink.trasse-ausfuehrung.html#/nbr.onelink.trasse-ausfuehrung-trasse/%257B...
     *     -> nbr.onelink.trasse-ausfuehrung-trasse   (real page route)
     *   /onelink.bmdb.alle-massnahmen.html#/onelink.bmdb.alle-massnahmen.DataTable_..._Dialog/...
     *     -> onelink.bmdb.alle-massnahmen            (dialog route, the page did not change)
     */
    public function getPageAliasFromCurrentUrl(): ?string
    {
        // Resolve the alias of the physically loaded page FIRST: it is the reference needed to tell a
        // page route from a widget route in the fragment below.
        $aliasFromFile = null;
        $url = $this->getSession()->getCurrentUrl();
        if ($url !== '') {
            $parts = parse_url($url);
            if (!empty($parts['path'])) {
                $file = basename($parts['path']);
                if (str_ends_with($file, '.html')) {
                    $aliasFromFile = substr($file, 0, -5);
                }
            }
        }

        $hash = (string)$this->getSession()->evaluateScript('return window.location.hash || "";');
        if ($hash !== '' && $hash !== '#') {
            $hash = ltrim($hash, '#');
            $hash = ltrim($hash, '/');

            $alias = strtok($hash, '/');
            if ($alias !== false && $alias !== '') {
                $alias = urldecode($alias);
                if ($aliasFromFile !== null && StringDataType::startsWith($alias, $aliasFromFile . '.')) {
                    // Widget route (dialog, detail view, ...) inside the page we are already on.
                    return $aliasFromFile;
                }
                return $alias;
            }
        }

        return $aliasFromFile;
    }

    /**
     * Returns all visible tiles of the current page.
     *
     * WHY it goes through the scope helper: tiles are page-level by definition, so the focused-scope
     * logic of findWidgetNodes() does not apply, and building the nodes through the factory keeps tile
     * node resolution identical to every other widget type instead of hard-wiring UI5TileNode here.
     *
     * @return UI5TileNode[]
     */
    public function findTiles(): array
    {
        // Find tiles on the page
        $nodes = $this->findWidgets("Tile");

        // Store the tile names on the page
        $tiles = [];
        foreach ($nodes ?? [] as $node) {
            $tile = new UI5TileNode($node, $this->getSession(), $this);
            $tiles[] = $tile;
        }
        Assert::assertNotEmpty($tiles, 'No tiles found');
        return $tiles;
    }

    /**
     * Finds visible widgets of the given type anywhere on the current page.
     *
     * WHY it returns a list: the visibility filter used to be applied with array_filter(), which preserves
     * the original DOM keys. Callers indexing the result directly - e.g. $dataTables[0] in the "the DataTable
     * contains" step - then hit an undefined key whenever the first matching element happened to be hidden,
     * producing a PHP warning instead of the intended assertion failure. array_values() restores a real list.
     *
     * @param string $widgetType The type of widget to search for (e.g. 'DataTable')
     * @param string|null $objectAlias Reserved - see the note below, currently NOT applied as a filter
     * @param int $timeoutInSeconds Maximum time to wait for the widgets to appear
     *
     * @return NodeElement[] Visible widget elements matching the search criteria
     */
    public function findWidgets(string $widgetType, int $timeoutInSeconds = 10): array
    {
        // Let the UI settle FIRST: buildCssSelectorForWidgetType() discovers subtypes by scanning the
        // live DOM, so resolving it against a DOM that is still rendering would silently collapse the
        // selector back to the plain type and drop every specialised variant again.
        $this->waitManager->waitForPendingOperations(true, true, true);

        if ($timeoutInSeconds > 0) {
            // waitForDOMElements() takes ($cssSelector, $number, $timeoutInSeconds). The timeout used to be
            // passed as the second argument, so the generated condition became "length >= <timeout>" and the
            // call waited for as many elements as there were seconds in the timeout - which almost never
            // becomes true. Every lookup therefore burned the full default timeout before returning, even
            // when the widget had been in the DOM from the start.
            $this->waitManager->waitForDOMElements(
                $this->buildCssSelectorForWidgetType($widgetType),
                1,
                $timeoutInSeconds
            );
        }

        // Resolve once more after the wait - subtypes may have appeared only during it.
        $cssSelector = $this->buildCssSelectorForWidgetType($widgetType);

        $visibleWidgets = array_filter($this->getPage()->findAll('css', $cssSelector), function ($widget) {
            return $widget->isVisible();
        });

        return array_values($visibleWidgets);
    }

    /**
     * Returns the type of the widget, that the given node belongs to
     *
     * @param NodeElement $node
     * @return bool|string|null
     */
    public function getNodeWidgetType(NodeElement $node): ?string
    {
        $classes = $node->getAttribute('class');
        $type = null;
        foreach (explode(' ', $classes ?? '') as $class) {
            if (mb_stripos($class, 'exfw-') === 0) {
                $type = StringDataType::substringAfter($class, 'exfw-');
            }
        }
        if ($type === null) {
            // TODO search the parents of the node for the first one with `exfw` CSS class
            // and take the widget type from that node
        }
        return $type;
    }

    public function getTestingUsername(): string
    {
        $config = $this->getWorkbench()->getApp('axenox.BDT')->getConfig();
        return $config->getOption('TEST_USER.USERNAME');
    }

    /**
     * Returns the id of the DOM element / UI5 control the facade renders for the given widget.
     *
     * WHY the id is computed instead of read from a facade element: asking the facade for an element
     * builds the whole thing - init() runs, controller dependencies get registered, external modules
     * are pulled in. Outside a real rendering request there is no controller, so elements that touch
     * it while initialising (UI5Markdown registers its editor there) abort with
     * "No controller was initialized for page ...". A test only needs the id, not a renderable
     * element, so it must not pay that price.
     *
     * WHY it is safe to rebuild the scheme here: it consists of exactly two steps, both taken from
     * the facade itself - the page UID without its leading character (UI5AbstractElement::getId())
     * and cleanId(), which replaces the characters the facade config declares forbidden with "_".
     * The dot matters most: UiPage uses it as its id space separator, so a widget id like
     * "..._DataButton05.VerortungId" is rendered as "..._DataButton05_VerortungId". Reading the
     * character list from the facade config keeps this in sync if the facade ever changes it.
     *
     * @param WidgetInterface $widget
     * @return string
     */
    public function getElementIdFromWidget(WidgetInterface $widget) : string
    {
        $forbiddenChars = $this->getFacade()
            ->getConfig()
            ->getOption('WIDGET.ALL.FORBIDDEN_CHARS_IN_ELEMENT_ID')
            ->toArray();
        return substr($widget->getPage()->getUid(), 1)
            . '__'
            . str_replace($forbiddenChars, '_', $widget->getId());
    }

    /**
     * Gets the UI5Facade instance used for UI5-specific operations
     * Lazy-loads the facade if not already instantiated
     *
     * WHY the explicit instance check: FacadeFactory::createFromString() is declared to return the
     * generic FacadeInterface, so assigning its result to a UI5Facade-typed property is not provable
     * for static analysis. Narrowing here documents the expectation and turns a wrong selector into a
     * named error instead of a type error deep inside the first element call.
     *
     * @return UI5Facade UI5 facade instance
     */
    public function getFacade(): UI5Facade
    {
        if ($this->facade === null) {
            $facade = FacadeFactory::createFromString(UI5Facade::class, $this->getWorkbench());
            if (!$facade instanceof UI5Facade) {
                throw new RuntimeException('Cannot initialize the UI5 facade: got "' . get_class($facade) . '" instead of ' . UI5Facade::class . '.');
            }
            $this->facade = $facade;
        }
        return $this->facade;
    }

    /**
     * Since UI5 combines pages one after another, there are a lot of back button
     * so instead of using the back buton, window history back was used
     */
    public function navigateToPreviousPage(): void
    {
        $this->getSession()->executeScript('window.history.back();');
        $this->getWaitManager()->waitForPendingOperations(true, true, true);
    }

    /**
     * Gets the wait manager instance that handles all wait operations
     *
     * @return UI5WaitManager The wait manager instance
     */
    public function getWaitManager(): UI5WaitManager
    {
        return $this->waitManager;
    }

    public function getPageCurrent(): ?UiPageInterface
    {
        $this->syncUiNavigation();
        $pageAlias = end($this->pagesVisited);
        return UiPageFactory::createFromModel($this->getWorkbench(), $pageAlias);
    }

    /**
     * Fills the internal history of this class from the current JS state
     *
     * @return string
     * @throws Exception
     */
    protected function syncUiNavigation(): string
    {
        $this->getWaitManager()->waitForPendingOperations(true, true, true);
        $pageAlias = $this->getPageAliasFromCurrentUrl();
        if (!$pageAlias) {
            throw new \RuntimeException('Cannot determine current page alias after UI navigation.');
        }

        $prevAlias = end($this->pagesVisited);
        if ($prevAlias !== $pageAlias) {
            $this->getEventDispatcher()->dispatch(new AfterPageVisited($pageAlias));
            $this->pagesVisited[] = $pageAlias;
        }

        return $pageAlias;
    }

    /**
     * Inject screenshot function from context.
     *
     * @param callable $fn function(string $reason, array $meta): ?ScreenshotInfo
     */
    public function setScreenshotFn(callable $fn): void
    {
        $this->screenshotFn = $fn;
    }

    /**
     * Takes a screenshot of the current browser state through the callback wired by the context.
     *
     * WHY the reason is written to the logbook and not only to ErrorManager: the report shows the
     * logbook right next to the failed step, while an ErrorManager entry lives somewhere else
     * entirely. Without this line a missing picture is indistinguishable from a picture that was
     * never requested - which is how a broken screenshot path stayed invisible for whole runs.
     *
     * WHY it still swallows the throwable: it is called from failure handling, and a screenshot that
     * cannot be stored must never replace the original test failure.
     *
     * @param LogBookInterface|null $logbook Logbook of the failing step, if the caller has one
     * @return void
     */
    public function captureScreenshot(?LogBookInterface $logbook = null): void
    {
        if ($this->screenshotFn === null) {
            $logbook?->addLine('**WARNING:** No screenshot stored - no screenshot callback is wired into the browser.');
            return;
        }

        try {
            ($this->screenshotFn)();
        } catch (Throwable $e) {
            $logbook?->addLine('**WARNING:** No screenshot stored: ' . $e->getMessage());
            ErrorManager::getInstance()->logException($e, $this->getWorkbench());
        }
    }

    /**
     * Logs out the current browser session by calling the ExFace Logout action via
     * synchronous XHR from within the browser. This ensures the HttpOnly session
     * cookie is sent automatically without any page navigation.
     */
    public function logOutIfAlreadyLoggedIn($baseUrl): void
    {
        $webapp = $this->findAppFromUrl($this->getSession()->getCurrentUrl());
        $apiUrl = rtrim($baseUrl, '/') . '/api/ui5';
        $this->getSession()->evaluateScript(<<<JS
        (function() {
            var xhr = new XMLHttpRequest();
            xhr.open('POST', '$apiUrl', false);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
            xhr.send('action=exface.Core.Logout&resource=$webapp&webapp=$webapp');
        })();
    JS
        );
    }

    public function findAppFromUrl(string $currentUrl): string
    {
        $pagePath = basename(parse_url($currentUrl, PHP_URL_PATH));
        return preg_replace('/\.html$/', '', $pagePath);
    }

    /**
     * Attempts to close any SAP UI5 error dialog currently blocking the DOM.
     *
     * Called from the abstract node layer immediately after the screenshot is captured,
     * so the dialog is still visible in the screenshot but no longer blocks subsequent
     * back-navigation or teardown interactions.
     *
     * Uses SAP UI5's own control API (sap.ui.getCore().byId().close()) rather than
     * native .click(), because UI5 buttons bypass the browser's native click handler
     * and route events through their own delegation system.
     *
     * @return bool True if a dialog was found and dismissed, false if none was present.
     */
    public function dismissErrorDialogIfPresent(): bool
    {
        $dismissed = $this->getSession()->evaluateScript(<<<'JS'
(function () {
    // Target the SAP UI5 error dialog — class 'sapMDialogError' is always present
    // on sap.m.Dialog instances rendered with type MessageType.Error.
    var dialog = document.querySelector('.sapMDialogError');
    if (!dialog) return false;

    var controlId = dialog.getAttribute('id');
    if (controlId && typeof sap !== 'undefined') {
        var control = sap.ui.getCore().byId(controlId);
        if (control && typeof control.close === 'function') {
            control.close();
            return true;
        }
    }

    // Fallback: trigger the designated end-button directly for custom dialog layouts
    // where the control API may not be available (e.g. unit-test stubs).
    var closeBtn = dialog.querySelector('button.sapMDialogEndButton');
    if (!closeBtn) {
        var buttons = dialog.querySelectorAll('button');
        for (var i = 0; i < buttons.length; i++) {
            var txt = (buttons[i].innerText || buttons[i].textContent || '').trim().toLowerCase();
            if (txt === 'close' || txt === 'schließen' || txt === 'schliessen') {
                closeBtn = buttons[i];
                break;
            }
        }
    }
    if (closeBtn) { closeBtn.click(); return true; }

    return false;
})();
JS
        );

        return (bool)$dismissed;
    }

    /**
     * Registers the Chrome recovery callback from UI5BrowserContext.
     * Nodes deep in the tree (e.g. UI5ContainerNode) need to trigger a Chrome restart
     * but have no direct reference to the context. This callback bridges that gap,
     * following the same pattern as setNavigator() and setScreenshotFn().
     * The callable receives the target page alias to navigate to after recovery.
     */
    public function setChromeRecoveryFn(callable $fn): void
    {
        $this->chromeRecoveryFn = $fn;
    }

    /**
     * Invokes the Chrome recovery callback registered via setChromeRecoveryFn().
     * Called by UI5ContainerNode when a ChromeHangException is caught mid-iteration.
     * The actual restart, re-login and navigation are performed by UI5BrowserContext::recoverChrome().
     *
     * @param string $targetPageAlias The container page to navigate to after recovery,
     *                                so the retry can find child DOM elements again.
     */
    public function recoverChrome(string $targetPageAlias): void
    {
        if ($this->chromeRecoveryFn === null) {
            throw new \RuntimeException('Chrome recovery callback not configured. Call setChromeRecoveryFn() first.');
        }
        ($this->chromeRecoveryFn)($targetPageAlias);
    }
}