# Default profile
default:
  autoload:
      # Point the PSR-0 autoloader built into Behat to our verndor folder. This will allow it to find
      # the different contexts by their namespace
      '': '%paths.base%/vendor'
  suites:
    default:
      contexts:
        - axenox\BDT\Tests\Behat\Contexts\UI5Facade\FeatureContext
  extensions:
    # Chrome UI driver
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    # Base extension for UI tests
    Behat\MinkExtension:  
      # The different session type can be configured in axenox.Behat.config.json in the BROWSERS section
      # Stick with chrome by default. It's 2x faster than firefox or phantomjs (your results may vary).
      default_session: CHROME_DEBUG_API
      javascript_session: CHROME_DEBUG_API
      # Configure browser to be used. Browser must be available on wd_host.
      sessions:
        # Chrome portable as described in the docs
        CHROME_DEBUG_API:
          chrome:
              api_url: "http://localhost:9222"
              # Increase timeout because the first time chrome is called it might take longer
              socket_timeout: 30
        # Selenium - worked only with Selenium 2 which is outdated and does not work with current browsers
        SELENIUM:
          selenium2: # or selenium4?
              wd_host: http://127.0.0.1:4444
              capabilities:
                    browserName: firefox
                    version: "*"
                    platform: ANY
        # Non-Javascript browser via Symfony browserkit. Should be faster. Not tested yet
        # BROWSERKIT:
          # browserkit_http: ~
          