# Default profile for Behat configuration
default:
 # Formatters section defines how test results will be reported
 formatters:
   # Pretty formatter provides readable console output with colors and formatting
   pretty: true
   # HTML formatter generates detailed test reports in web format
   html:
     # Directory where HTML test reports will be saved
     # Using paths.base ensures reports are saved relative to project root
     output_path: '%paths.base%/data/axenox/BDT/Reports' 
 
 autoload:
     # Configure PSR-0 autoloader to find test context classes
     # Empty prefix means look in all namespaces under vendor directory
     # This helps Behat locate all required testing classes automatically
     '': '%paths.base%/vendor'
 
 suites:
   # Default test suite configuration
   default:
     contexts:
       # List of context classes that provide test steps
       # UI5BrowserContext handles UI5-specific testing functionality
       - axenox\BDT\Tests\Behat\Contexts\UI5Facade\UI5BrowserContext
     # Timeout and failure handling settings
     stop_on_failure: false    # Continue testing even if a test fails
     fail_on_timeout: false    # Don't mark test as failed on timeout
     timeouts:
       suite: 1800    # 30 minutes timeout for entire test suite
       step: 300      # 5 minutes timeout for individual steps
       scenario: 600  # 10 minutes timeout for each scenario
 
 extensions:
  # Chrome Extension for Behat - enables Chrome WebDriver integration
  DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
  
  # MinkExtension provides browser automation capabilities
  Behat\MinkExtension:  
  
    # Session configuration for browser automation
    # Using Chrome as default browser due to better performance
    default_session: CHROME_DEBUG_API
    javascript_session: CHROME_DEBUG_API
    
    # Browser session configurations
    sessions:
      # Chrome Debug Protocol configuration
      # Uses Chrome's debugging API for better control and stability
      CHROME_DEBUG_API:
        chrome:
          # Chrome debugging API endpoint
          api_url: "http://localhost:9222"
          # Extended timeout for initial Chrome startup
          # Particularly important for first test run
          socket_timeout: 120 # 2 minutes 
      
      # Selenium WebDriver configuration (legacy support)
      # Note: Selenium 2 is outdated, consider upgrading to Selenium 4
      SELENIUM:
        selenium2:
          wd_host: http://127.0.0.1:4444
          capabilities:
            browserName: firefox
            version: "*"
            platform: ANY
      
      # Browserkit configuration for lightweight testing (experimental)
      # Commented out as it's not fully tested yet
      # BROWSERKIT:
        # browserkit_http: ~
   
  # HTML Formatter extension settings
  # Generates detailed HTML reports for test results
  axenox\BDT\Behat\TwigFormatter\BehatFormatterExtension:
    projectName: axenox BDT
    name: html
    renderer: Twig
    # file_name: Index
    print_args: true
    print_outp: true
    loop_break: true
    show_tags: true
